routes/web.php
<?php

use App\Http\Controllers\Controller;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Route::resource('/operational', \App\Http\Controllers\OperationalController::class)->middleware('auth');

Route::middleware(['auth'])->namespace('Main')->group(function () {
    Route::get('/admin/home', 'HomeController@index')->name('admin.home.index');
    Route::resource('/admin/user', 'UserController');
    Route::resource('/admin/operational', 'OperationalController');
    Route::get('/admin/revenue', 'RevenueController@index')->name('admin.revenue.index');

    // Route::get('/admin/operational', 'Controller@index')->name('admin.operational');

});

app/Models/Operational.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Operational extends Model
{
    use HasFactory;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'item', 'price', 'notes', 'purchase_date'
    ];

    protected $dateFormat = 'U';
    protected $dates = ['created_at', 'updated_at', 'deleted_at'];
    protected $hidden = ['deleted_at'];
}

app/Http/Controllers/Main/OperationalController.php
<?php

namespace App\Http\Controllers\Main;

use App\Http\Controllers\Controller;
use App\Models\Operational;
use Illuminate\Http\Request;

class OperationalController extends Controller
{
    private $operational;

    function __construct(Operational $_operationalCost)
    {
        $this->operational = $_operationalCost;
    }
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $purchaseDateStart = $request->purchase_date_start;
        $purchaseDateEnd = $request->purchase_date_end;

        if ($purchaseDateStart && $purchaseDateEnd) {
            $costs = $this->operational->whereBetween('purchase_date', [$purchaseDateStart, $purchaseDateEnd])->get();
        } else {
            $costs = $this->operational->all();
        }

        $purchaseDateStart = $purchaseDateStart ?? date('Y-m-d');
        $purchaseDateEnd = $purchaseDateEnd ?? date('Y-m-d');

        return view('admin.operational.index', compact('costs', 'purchaseDateStart', 'purchaseDateEnd'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.operational.add');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $operational = Operational::create([
            'item' => $request->item,
            'price' => $request->price,
            'purchase_date' => $request->purchase_date,
            'notes' => $request->notes,
        ]);


        if ($operational) {
            return redirect(route('operational.index'));
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  \App\Models\Operational  $operational
     * @return \Illuminate\Http\Response
     */
    public function show(Operational $operational)
    {

        return view('admin.operational.show', compact('operational'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  \App\Models\Operational  $operational
     * @return \Illuminate\Http\Response
     */
    public function edit(Operational $operational)
    {
        return view('admin.operational.edit', compact('operational'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Models\Operational  $operational
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Operational $operational)
    {
        $operational->item = $request->item;
        $operational->price = $request->price;
        $operational->purchase_date = $request->purchase_date;
        $operational->notes = $request->notes;

        if ($operational->save()) {
            return redirect(route('operational.index'));
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  \App\Models\Operational  $operational
     * @return \Illuminate\Http\Response
     */
    public function destroy(Operational $operational)
    {
        if ($operational->delete()) {
            return redirect(route('operational.index'));
        }
    }
}

resources/views/admin/operational/add.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="card">
                <div class="card-header text-white bg-primary">Add New Operational Cost</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('operational.store') }}">
                        @csrf
                        <div class="mb-3 row">
                            <label class="col-sm-2 col-form-label">Item</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="item">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label class="col-sm-2 col-form-label">Price</label>
                            <div class="col-sm-10">
                                <input type="number" class="form-control" name="price">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label class="col-sm-2 col-form-label">Purchase Date</label>
                            <div class="col-sm-10">
                                <input type="date" class="form-control" name="purchase_date">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label class="col-sm-2 col-form-label">Notes</label>
                            <div class="col-sm-10">
                                <textarea class="form-control" name="notes"></textarea>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="{{route('operational.index')}}" type="button" class="btn btn-primary" style="float: right">Back</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/operational/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="card">
                <div class="card-header text-white bg-primary">Edit Operational Cost</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('operational.update', $operational->id) }}">
                        @method('PUT')
                        @csrf
                        <div class="mb-3 row">
                            <label class="col-sm-2 col-form-label">Item</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="item" value="{{$operational->item}}">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label class="col-sm-2 col-form-label">Price</label>
                            <div class="col-sm-10">
                                <input type="number" class="form-control" name="price" value="{{$operational->price}}">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label class="col-sm-2 col-form-label">Purchase Date</label>
                            <div class="col-sm-10">
                                <input type="date" class="form-control" name="purchase_date" value="{{$operational->purchase_date ?? date('Y-m-d')}}">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label class="col-sm-2 col-form-label">Notes</label>
                            <div class="col-sm-10">
                                <textarea class="form-control" name="notes">{{$operational->notes}}</textarea>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Edit</button>
                        <a href="{{route('operational.index')}}" type="button" class="btn btn-primary" style="float: right">Back</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/operational/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h5>Operational</h5>
                </div>
                <div class="card-body">
                    <div class="col d-flex align-items-center justify-content-between">
                        <a type="button" class="btn btn-sm btn-primary" href="{{ route('operational.create') }}">Add New</a>
                        <form class="form-inline my-2 my-lg-0">
                            <form method="GET" action="{{ route('operational.index') }}">
                                <input type="date" name="purchase_date_start" value="{{ $purchaseDateStart}}">
                                <input type="date" name="purchase_date_end" value="{{ $purchaseDateEnd}}">
                                <input type="submit" class="btn btn-sm btn-primary" value="filter">
                            </form>
                        </form>
                    </div>
                    <br>
                    <table class="table">
                        <thead class="table-dark" style="background-color: #718096;">
                            <tr>
                                <th scope="col">Nomor</th>
                                <th scope="col">Item</th>
                                <th scope="col">Price</th>
                                <th scope="col">Notes</th>
                                <th scope="col">Purchase Date</th>
                                <th scope="col"></th>
                                <th scope="col"></th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($costs as $key => $cost)
                            <tr>
                                <th scope="row">{{ $key+1 }}</th>
                                <td>{{ $cost->item }}</td>
                                <td>{{ $cost->price }}</td>
                                <td>{{ $cost->notes }}</td>
                                <td>{{ $cost->purchase_date }}</td>
                                <td>
                                    <div class="row">
                                        <div class="col-12">
                                            <a type="btn" class="btn btn-sm btn-info" href="{{route('operational.show', $cost->id)}}">Show</a>
                                            <a type="btn" class="btn btn-sm btn-primary" href="{{route('operational.edit', $cost->id)}}">Edit</a>
                                        </div>
                                    </div>
                                </td>
                                <td>
                                    <div class="row">
                                        <div class="col-12">
                                            <form method="POST" action="{{ route('operational.destroy', $cost->id) }}">
                                                @method('delete')
                                                @csrf
                                                <input type="submit" class="btn btn-sm btn-danger" value="delete">
                                            </form>
                                        </div>
                                    </div>
                                </td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/operational/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="card">
                <div class="card-header text-white bg-primary">Show Operational Cost</div>
                <div class="card-body">
                    <div class="mb-3 row">
                        <label class="col-sm-2 col-form-label">Item</label>
                        <div class="col-sm-10">
                            <p>{{$operational->item}}</p>
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <label class="col-sm-2 col-form-label">Price</label>
                        <div class="col-sm-10">
                            <p>{{$operational->price}}</p>
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <label class="col-sm-2 col-form-label">Purchase Date</label>
                        <div class="col-sm-10">
                            <p>{{$operational->purchase_date}}</p>
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <label class="col-sm-2 col-form-label">Notes</label>
                        <div class="col-sm-10">
                            <p>{{$operational->notes}}</p>
                        </div>
                    </div>
                    <a href="{{route('operational.index')}}" type="button" class="btn btn-primary" style="float: right">Back</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection