routes/web.php
<?php

use App\Http\Controllers\Controller;
use App\Http\Controllers\HomeController;
use Illuminate\Support\Facades\Route;
use Illuminate\Support\Facades\Auth;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

// Route::get('/home', [App\Http\Controllers\HomeController::class, 'index'])->name('home');

// Route::resource('/operational', \App\Http\Controllers\OperationalController::class)->middleware('auth');

Route::middleware(['auth'])->namespace('Main')->group(function () {
    Route::get('/admin/home', 'HomeController@index')->name('admin.home.index');
    Route::resource('/admin/user', 'UserController');
    Route::resource('/admin/operational', 'OperationalController');
    Route::get('/admin/revenue', 'RevenueController@index')->name('admin.revenue.index');

    // Route::get('/admin/operational', 'Controller@index')->name('admin.operational');

});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Sanctum\HasApiTokens;

class User extends Authenticatable
{
    use HasApiTokens, HasFactory, Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array<int, string>
     */
    protected $fillable = [
        'name',
        'email',
        'password',
    ];

    /**
     * The attributes that should be hidden for serialization.
     *
     * @var array<int, string>
     */
    protected $hidden = [
        'password',
        'remember_token',
    ];

    /**
     * The attributes that should be cast.
     *
     * @var array<string, string>
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function access()
    {
        return $this->belongsTo(Access::class);
    }
}

app/Http/Controllers/Main/UserController.php
<?php

namespace App\Http\Controllers\Main;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\Access;

class UserController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $accesses = $this->checkAccesses();

        $access = User::all();
        return view('admin.user.index', compact('access', 'accesses'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $accesses = $this->checkAccesses();
        $accessAll = Access::all();
        return view('admin.user.add', compact('accessAll'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $accesses = $this->checkAccesses();
        $isExist = User::where('email', $request->email)->first();
        if ($isExist) {
            echo 'email already exists';
        } else {
            $user = new User();
            $user->name = $request->name;
            $user->email = $request->email;
            $user->password = password_hash("admin123", PASSWORD_BCRYPT);
            $user->access_id = $request->access_id;

            if ($user->save()) {
                return redirect(route('user.index'));
            }
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $this->checkAccesses();
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $this->checkAccesses();
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->checkAccesses();
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $this->checkAccesses();
    }

    private function checkAccesses()
    {
        $userAccesses = auth()->user()->access->name ?? null;
        if ($userAccesses !== 'owner') {
            abort(404);
        }
        return true;
    }
}

resources/views/admin/user/add.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="card">
                <div class="card-header text-white bg-primary">Add New User</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('user.store') }}">
                        @csrf
                        <div class="mb-3 row">
                            <label class="col-sm-2 col-form-label">Name</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="name">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label class="col-sm-2 col-form-label">Email</label>
                            <div class="col-sm-10">
                                <input type="mail" class="form-control" name="email">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label class="col-sm-2 col-form-label">Access</label>
                            <div class="col-sm-10">
                                <select name="access_id" class="form-control">
                                    @foreach ($accessAll as $value)
                                    <option value="{{$value->id}}">{{$value->name}}</option>
                                    @endforeach
                                </select>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Submit</button>
                        <a href="{{route('operational.index')}}" type="button" class="btn btn-primary" style="float: right">Back</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="card">
                <div class="card-header text-white bg-primary">Edit Operational Cost</div>
                <div class="card-body">
                    <form method="POST" action="{{ route('operational.update', $operational->id) }}">
                        @method('PUT')
                        @csrf
                        <div class="mb-3 row">
                            <label class="col-sm-2 col-form-label">Item</label>
                            <div class="col-sm-10">
                                <input type="text" class="form-control" name="item" value="{{$operational->item}}">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label class="col-sm-2 col-form-label">Price</label>
                            <div class="col-sm-10">
                                <input type="number" class="form-control" name="price" value="{{$operational->price}}">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label class="col-sm-2 col-form-label">Purchase Date</label>
                            <div class="col-sm-10">
                                <input type="date" class="form-control" name="purchase_date" value="{{$operational->purchase_date ?? date('Y-m-d')}}">
                            </div>
                        </div>
                        <div class="mb-3 row">
                            <label class="col-sm-2 col-form-label">Notes</label>
                            <div class="col-sm-10">
                                <textarea class="form-control" name="notes">{{$operational->notes}}</textarea>
                            </div>
                        </div>
                        <button type="submit" class="btn btn-primary">Edit</button>
                        <a href="{{route('operational.index')}}" type="button" class="btn btn-primary" style="float: right">Back</a>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/index.blade.php
@extends('layouts.app')

@section('content')
<div class="container" id="user-index">
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <h5>Users</h5>
                </div>
                <div class="card-body">
                    <div class="col d-flex align-items-center justify-content-between">
                        <a type="button" class="btn btn-sm btn-primary" href="{{ route('user.create') }}">Add New</a>
                    </div>
                    <br>
                    <table class=" table">
                        <thead class="table-dark" style="background-color: #718096;">
                            <tr>
                                <th scope="col">Nomor</th>
                                <th scope="col">Name</th>
                                <th scope="col">Email</th>
                                <th scope="col">Access</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($access as $key => $value)
                            <tr>
                                <th scope="row">{{ $value->id }}</th>
                                <td>{{ $value->name }}</td>
                                <td>{{ $value->email }}</td>
                                <td>{{ $value->access->name ?? '-' }}</td>
                            </tr>
                            @endforeach
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/admin/user/show.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-12">
            <div class="card">
                <div class="card-header text-white bg-primary">Show Operational Cost</div>
                <div class="card-body">
                    <div class="mb-3 row">
                        <label class="col-sm-2 col-form-label">Item</label>
                        <div class="col-sm-10">
                            <p>{{$operational->item}}</p>
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <label class="col-sm-2 col-form-label">Price</label>
                        <div class="col-sm-10">
                            <p>{{$operational->price}}</p>
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <label class="col-sm-2 col-form-label">Purchase Date</label>
                        <div class="col-sm-10">
                            <p>{{$operational->purchase_date}}</p>
                        </div>
                    </div>
                    <div class="mb-3 row">
                        <label class="col-sm-2 col-form-label">Notes</label>
                        <div class="col-sm-10">
                            <p>{{$operational->notes}}</p>
                        </div>
                    </div>
                    <a href="{{route('operational.index')}}" type="button" class="btn btn-primary" style="float: right">Back</a>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection